package com.sbnz.berza.model;
// Generated Jun 25, 2020 11:56:39 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Table(name = "buyer", catalog = "sbnz")
public class Buyer implements java.io.Serializable {

	private Long buyerId;
	private Buyeraccount buyeraccount;
	private String buyerName;
	private String buyerSurname;
	private long zaduzenja;
	private long prviPutDolazi;
	private Set offers = new HashSet(0);
	private Set falseproducts = new HashSet(0);
	private Set buyeraccounts = new HashSet(0);
	private Set sales = new HashSet(0);

	public Buyer() {
	}

	public Buyer(String buyerName, String buyerSurname, long zaduzenja, long prviPutDolazi) {
		this.buyerName = buyerName;
		this.buyerSurname = buyerSurname;
		this.zaduzenja = zaduzenja;
		this.prviPutDolazi = prviPutDolazi;
	}

	public Buyer(Buyeraccount buyeraccount, String buyerName, String buyerSurname, long zaduzenja, long prviPutDolazi,
			Set offers, Set falseproducts, Set buyeraccounts, Set sales) {
		this.buyeraccount = buyeraccount;
		this.buyerName = buyerName;
		this.buyerSurname = buyerSurname;
		this.zaduzenja = zaduzenja;
		this.prviPutDolazi = prviPutDolazi;
		this.offers = offers;
		this.falseproducts = falseproducts;
		this.buyeraccounts = buyeraccounts;
		this.sales = sales;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BUYER_ID", unique = true, nullable = false)
	public Long getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(Long buyerId) {
		this.buyerId = buyerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUYER_ACCOUNT_ID")
	public Buyeraccount getBuyeraccount() {
		return this.buyeraccount;
	}

	public void setBuyeraccount(Buyeraccount buyeraccount) {
		this.buyeraccount = buyeraccount;
	}

	@Column(name = "BUYER_NAME", nullable = false, length = 100)
	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	@Column(name = "BUYER_SURNAME", nullable = false, length = 250)
	public String getBuyerSurname() {
		return this.buyerSurname;
	}

	public void setBuyerSurname(String buyerSurname) {
		this.buyerSurname = buyerSurname;
	}

	@Column(name = "ZADUZENJA", nullable = false)
	public long getZaduzenja() {
		return this.zaduzenja;
	}

	public void setZaduzenja(long zaduzenja) {
		this.zaduzenja = zaduzenja;
	}

	@Column(name = "PRVI_PUT_DOLAZI", nullable = false)
	public long getPrviPutDolazi() {
		return this.prviPutDolazi;
	}

	public void setPrviPutDolazi(long prviPutDolazi) {
		this.prviPutDolazi = prviPutDolazi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set getFalseproducts() {
		return this.falseproducts;
	}

	public void setFalseproducts(Set falseproducts) {
		this.falseproducts = falseproducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set getBuyeraccounts() {
		return this.buyeraccounts;
	}

	public void setBuyeraccounts(Set buyeraccounts) {
		this.buyeraccounts = buyeraccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set getSales() {
		return this.sales;
	}

	public void setSales(Set sales) {
		this.sales = sales;
	}

}
