package com.sbnz.berza.model;
// Generated Jun 25, 2020 11:56:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Falseproduct generated by hbm2java
 */
@Entity
@Table(name = "falseproduct", catalog = "sbnz")
public class Falseproduct implements java.io.Serializable {

	private Long fpId;
	private Buyer buyer;
	private Product product;

	public Falseproduct() {
	}

	public Falseproduct(Buyer buyer, Product product) {
		this.buyer = buyer;
		this.product = product;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FP_ID", unique = true, nullable = false)
	public Long getFpId() {
		return this.fpId;
	}

	public void setFpId(Long fpId) {
		this.fpId = fpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUYER_ID", nullable = false)
	public Buyer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
