package com.sbnz.berza.model;
// Generated Jun 25, 2020 11:56:39 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "sbnz")
public class Product implements java.io.Serializable {

	private Long productId;
	private String productName;
	private String productCode;
	private long zadovoljavaStandarde;
	private long pouzdanProizvodjac;
	private long prosaoAnalizu;
	private Set offers = new HashSet(0);
	private Set falseproducts = new HashSet(0);
	private Set sales = new HashSet(0);
	private Set productqualityparams = new HashSet(0);

	public Product() {
	}

	public Product(String productName, String productCode, long zadovoljavaStandarde, long pouzdanProizvodjac,
			long prosaoAnalizu) {
		this.productName = productName;
		this.productCode = productCode;
		this.zadovoljavaStandarde = zadovoljavaStandarde;
		this.pouzdanProizvodjac = pouzdanProizvodjac;
		this.prosaoAnalizu = prosaoAnalizu;
	}

	public Product(String productName, String productCode, long zadovoljavaStandarde, long pouzdanProizvodjac,
			long prosaoAnalizu, Set offers, Set falseproducts, Set sales, Set productqualityparams) {
		this.productName = productName;
		this.productCode = productCode;
		this.zadovoljavaStandarde = zadovoljavaStandarde;
		this.pouzdanProizvodjac = pouzdanProizvodjac;
		this.prosaoAnalizu = prosaoAnalizu;
		this.offers = offers;
		this.falseproducts = falseproducts;
		this.sales = sales;
		this.productqualityparams = productqualityparams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRODUCT_ID", unique = true, nullable = false)
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "PRODUCT_NAME", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_CODE", nullable = false, length = 10)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "ZADOVOLJAVA_STANDARDE", nullable = false)
	public long getZadovoljavaStandarde() {
		return this.zadovoljavaStandarde;
	}

	public void setZadovoljavaStandarde(long zadovoljavaStandarde) {
		this.zadovoljavaStandarde = zadovoljavaStandarde;
	}

	@Column(name = "POUZDAN_PROIZVODJAC", nullable = false)
	public long getPouzdanProizvodjac() {
		return this.pouzdanProizvodjac;
	}

	public void setPouzdanProizvodjac(long pouzdanProizvodjac) {
		this.pouzdanProizvodjac = pouzdanProizvodjac;
	}

	@Column(name = "PROSAO_ANALIZU", nullable = false)
	public long getProsaoAnalizu() {
		return this.prosaoAnalizu;
	}

	public void setProsaoAnalizu(long prosaoAnalizu) {
		this.prosaoAnalizu = prosaoAnalizu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getFalseproducts() {
		return this.falseproducts;
	}

	public void setFalseproducts(Set falseproducts) {
		this.falseproducts = falseproducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getSales() {
		return this.sales;
	}

	public void setSales(Set sales) {
		this.sales = sales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getProductqualityparams() {
		return this.productqualityparams;
	}

	public void setProductqualityparams(Set productqualityparams) {
		this.productqualityparams = productqualityparams;
	}

}
