package com.sbnz.berza.model;
// Generated Jun 25, 2020 11:56:39 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "sbnz")
public class User implements java.io.Serializable {

	private Long userId;
	private String userName;
	private String userSurname;
	private String userUsername;
	private String userPassword;
	private char userType;
	private long zaposlen;
	private long prodaoSveUsepsno;
	private Set sales = new HashSet(0);
	private Set offers = new HashSet(0);

	public User() {
	}

	public User(String userName, String userSurname, String userUsername, String userPassword, char userType,
			long zaposlen, long prodaoSveUsepsno) {
		this.userName = userName;
		this.userSurname = userSurname;
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userType = userType;
		this.zaposlen = zaposlen;
		this.prodaoSveUsepsno = prodaoSveUsepsno;
	}

	public User(String userName, String userSurname, String userUsername, String userPassword, char userType,
			long zaposlen, long prodaoSveUsepsno, Set sales, Set offers) {
		this.userName = userName;
		this.userSurname = userSurname;
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userType = userType;
		this.zaposlen = zaposlen;
		this.prodaoSveUsepsno = prodaoSveUsepsno;
		this.sales = sales;
		this.offers = offers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_ID", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_SURNAME", nullable = false, length = 200)
	public String getUserSurname() {
		return this.userSurname;
	}

	public void setUserSurname(String userSurname) {
		this.userSurname = userSurname;
	}

	@Column(name = "USER_USERNAME", nullable = false, length = 150)
	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	@Column(name = "USER_PASSWORD", nullable = false, length = 250)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 1)
	public char getUserType() {
		return this.userType;
	}

	public void setUserType(char userType) {
		this.userType = userType;
	}

	@Column(name = "ZAPOSLEN", nullable = false)
	public long getZaposlen() {
		return this.zaposlen;
	}

	public void setZaposlen(long zaposlen) {
		this.zaposlen = zaposlen;
	}

	@Column(name = "PRODAO_SVE_USEPSNO", nullable = false)
	public long getProdaoSveUsepsno() {
		return this.prodaoSveUsepsno;
	}

	public void setProdaoSveUsepsno(long prodaoSveUsepsno) {
		this.prodaoSveUsepsno = prodaoSveUsepsno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getSales() {
		return this.sales;
	}

	public void setSales(Set sales) {
		this.sales = sales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

}
